apiVersion: v1
kind: ConfigMap
metadata:
  name: survey-config
data:
  PORT: "8080"
  DATABASE_HOST: "postgresql.database.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_USER: "admin"
  DATABASE_NAME: "survey"
  DATABASE_SSLMODE: "disable"
  # OpenTelemetry
  OTEL_SERVICE_NAME: "survey-api"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.monitoring.svc.cluster.local:4318"
