apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-consumer
  labels:
    app: survey-consumer
spec:
  # Must be 1 - Jetstream requires single cursor
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: survey-consumer
  template:
    metadata:
      labels:
        app: survey-consumer
    spec:
      containers:
        - name: survey-consumer
          image: survey:latest
          command: ["/usr/local/bin/consumer"]
          envFrom:
            - configMapRef:
                name: survey-config
            - secretRef:
                name: survey-secrets
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
